name: .NET Build And Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore **/*.csproj
    
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: dotnet build **/*.csproj --no-restore
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: dotnet test **/*.csproj --no-build --verbosity normal
    - name: Self Defined UnitTests for release
      run: dotnet test StringLibraryTest/StringLibraryTest.csproj --no-build --configuration Release
